apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/Shop-Online.git
    path: app-of-apps/chart-aws-lbc
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: aws-alb-controller
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    # track and sync all git changes the argo will check every 3 minutes
    automated:
      selfHeal: true # auto sync the changes to the cluster from git
      prune: true    # auto delete resources locally if thay are not in git