#argo-cd:
  global:
    domain: argo-cd.spider-shlomo.com

  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      controller: aws
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/backend-protocol: HTTP
        alb.ingress.kubernetes.io/security-groups: sg-011ca41f253701b5f
        alb.ingress.kubernetes.io/subnets: subnet-09672c6cc819efd39,subnet-0c40539995bbdbfff # Public subnetbs
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:148088962203:certificate/8f5ab2d5-3865-4509-be23-6d81b5569f40
        alb.ingress.kubernetes.io/ssl-redirect: '443'
      aws:
        serviceType: ClusterIP # <- Used with target-type: ip
        backendProtocolVersion: GRPC