#argo-cd:
  global:
    domain: argo-cd.spider-shlomo.com

  configs:
    params:
      server.insecure: true
    oidc.config: |
      name: AzureAD
      issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
      clientID: CLIENT_ID
      clientSecret: $oidc.azuread.clientSecret
      rootCA: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDOERDQ0FkaWdBd0lCQWdJUVkrSU43TXQ2U1lsRzA2a1ZtL2ptb0RBTkJna3Foa2lHOXcwQkFRc0ZBREEwTVRJd01BWURWUVFEDQpFeWxOYVdOeWIzTnZablFnUVhwMWNtVWdSbVZrWlhKaGRHVmtJRk5UVHlCRFpYSjBhV1pwWTJGMFpUQWVGdzB5TkRFeU1qY3hNVE0zDQpNVFphRncweU56RXlNamN4TVRNM01UWmFNRFF4TWpBd0JnTlZCQU1US1UxcFkzSnZjMjltZENCQmVuVnlaU0JHWldSbGNtRjBaV1FnDQpVMU5QSUVObGNuUnBabWxqWVhSbE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNzdMbmovcEdzUXhPDQp1WW9pYlg1aDJpeCtxc1hPMC9OQTNiTEU1b0pWRWZWYk8vMDNYRDJ5UFJveG02VW5LZlIrVkR1UXBieXNmekdsaEoycENsMmYwaHhiDQpnbXVSMk91TTMvTEVpMlFkQ1pkMFM4V09OQTBCRTUxWm1pWUtCZzZMbGwyY1RGcU0vSGZ3OGhsSnN3OG4xWGF1VjQ5eXZmMUdUTWxODQpXMjhxa1RGSHZudlNKa256K0JacjNSM3N5ZXBYblorUVdWRXArQkRrQlc4dHY2QkZDckY0Qi9heVpWK05jRWRwYmJUZVVBbGhWT2JCDQpYaDc0RExReTdYYmZMMlRwU28yeVh6aGVRRkdjN1FMNG5YS3FQNHU4enIvTkFQMGNTcVZyOFkyZzlwcG1xb2xZUGNWZWFXMUV1aWZ5DQpQcUQvOUxoWDYzT3paRm1aUDNwNStBTFZzUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVRRM3pkekh2MUlJOFJIejRLDQpQNVFJaFhZWUczWkRMRkRRa3NtQjROTHdnSFVSUVVWOGYzR0xaKzFmWWR4bU9jQm54TllNbzYvdkxJVjlKTWc2QXNSYzNoclR6TjZNDQp6RVhqNTlydjF0VHdDdGlHREJ5MUdKUEdqbmJiZWNKeTJSZEJzaTVuQXhVWHJJVys1RkM2SGZ0RnEwNVJtbm1YUTdWb1lYK0JsTC9HDQpyNW5HZm5COUo0Nlp0N0RwdEc2Rkl2bVdJa1cwM1NFNWpmemQ2MVdaL05vSWkyQ0hseDZ4L2xYbnNML0ZhMVpROEhaVWdWWFVMVjYvDQptOHpYUEdQb1AxVXBDU3dwSHR4MWQrYk5UN3JwN3ltNWtkaCszZSsxNXRqQVM4SlNMUVgvam5SajFETEF3RFA3WG9PODV2eVA2VDBTDQpicVREWEtXTWZtL0RIZWxtR21uUw0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email  

  server:
    ingress:
      enabled: true
      controller: aws
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/backend-protocol: HTTP
        alb.ingress.kubernetes.io/security-groups: sg-09b52735903593977
        alb.ingress.kubernetes.io/subnets: subnet-06ecc8dce3939bc67,subnet-09e3ef8e74de1afaf # Public subnetbs
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:148088962203:certificate/19d27275-0e2a-4857-95e9-79dff8e8bbd3
        alb.ingress.kubernetes.io/ssl-redirect: '443'
      aws:
        serviceType: ClusterIP # <- Used with target-type: ip
        backendProtocolVersion: GRPC

        