apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecretstore
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:  # Note: using sources instead of source
    - repoURL: https://github.com/shlomo-b/project-blackjack.git
      path: ./app-of-apps/ClusterSecretStore
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      selfHeal: true  # auto sync the changes to the cluster from git
      prune: true     # auto delete resources locally if they are not in github
