apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-controller 
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/project-blackjack.git # the repo
    path: helm-charts/chart-aws-lbc # the path of the helm chart
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc  # The cluster URL Argo CD will connect to
    namespace: aws-alb-controller
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  # To automatically create the namespace if it doesn't exist
    automated:
      selfHeal: true  # Auto-sync changes from Git to the cluster
      prune: true     # Auto-delete resources that are not in Git