apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blackjack
  namespace: blackjack
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  selector:
    matchLabels:
      app: blackjack
  replicas: 2
  template:
    metadata:
      labels:
        app: blackjack
    spec:
      containers:      # שים לב לרמה הזו
      - name: blackjack
        image: shlomobarzili/blackjack:latest
        imagePullPolicy: Always     
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: blackjack-storage
          mountPath: /storage-data
      volumes:        # באותה רמה כמו containers!
      - name: blackjack-storage
        persistentVolumeClaim:
          claimName: blackjack-pvc