apiVersion: v1
kind: Service
metadata:
  name: svc-blackjack 
  namespace: blackjack # the namespace that sperate the pods between envroments.
spec:
  selector:
    app: blackjack
  type: ClusterIP # the type of the service
  ports:
    - protocol: TCP
      port: 80   # the port svc that expose
      targetPort: 80 # the port of the pod | container


---     
apiVersion: v1
kind: Service
metadata:
  name: svc-node-exporter
  namespace: blackjack
spec:
  selector:
    type: NodePort 
    node-exporter: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30910