apiVersion: v1
kind: Service
metadata:
  name: svc-blackjack 
  namespace: blackjack # the namespace that sperate the pods between envroments.
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    app: blackjack
  type: ClusterIP # the type of the service
  ports:
    - protocol: TCP
      port: 80   # the port svc that expose
      targetPort: 80 # the port of the pod | container