apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: blackjack
  namespace: blackjack

# bases:
#   - ../../_base
  
patchesStrategicMerge:
- storageclass.yml
- blackjack-deployment.yml
# - patch-service.yaml