apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackjack-pvc
  namespace: blackjack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 33Gi