apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: blackjack
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer # like pod affinity
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "33"
  encrypted: "true"
  tagSpecification_1: "key1=value1"
  tagSpecification_2: "key2=value2"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-1a

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: blackjack-pvc
#   namespace: blackjack
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-sc
#   resources:
#     requests:
#       storage: 33Gi