apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Correct URL for Bitnami Helm charts
    path: bitnami/external-dns
    targetRevision: 8.5.1  # Use the specific version of the chart
    chart: external-dns  # The Helm chart name
    helm:
      valueFiles:
        - ./values.yaml # Path to your custom values.yaml file
  destination:
    server: https://kubernetes.default.svc  # The cluster URL Argo CD will connect to
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  # To automatically create the namespace if it doesn't exist
    automated:
      selfHeal: true  # Auto-sync changes from Git to the cluster
      prune: true     # Auto-delete resources that are not in Git
