apiVersion: external-secrets.io/v1beta1
#kind: ClusterSecretStore
kind: SecretStore
metadata:
  name: aws-secret-store
#  namespace: lab4
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret # name of the secret from iam aws 
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret # name of the secret from iam aws 
            key: secret-access-key