apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lab4
spec:
  selector:
    matchLabels:
      app: backend-lab4
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-lab4
    spec:
      containers:
      - name: lab4-backend
        image: shlomobarzili/lab4-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5050
          protocol: TCP

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        env:
          - name: MONGO_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: variables-lab4
                key: MONGO_DB_HOST
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: aws-secret       # Kubernetes secret created by ExternalSecret
                key: DB-CREDENTIALS
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: aws-secret       # Kubernetes secret created by ExternalSecret
          #       key: MONGO_INITDB_ROOT_PASSWORD