# for working with alb type application you need to install helm and install the ingress controller aws.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blackjack
  namespace: blackjack # the namespace that sperate the pods  between envroments.
  annotations:
    kubernetes.io/ingress.class: alb # the type alb 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # the alb move the traffic directly to pods
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:148088962203:certificate/0cd45928-1c13-4e8a-af7e-c5e5000a97ad # the acm certificate arn
    alb.ingress.kubernetes.io/subnets: subnet-09bb39d76dbe368c7,subnet-052e8a55082e0399c # Public subnetbs
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]' # listen ports
    alb.ingress.kubernetes.io/actions.ssl-redirect: > # redirect to https
      {"type": "redirect", "redirectConfig": { "protocol": "HTTPS", "port": "443", "statusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
   # alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:us-east-1:148088962203:regional/webacl/blackjack-waf/ee177ef5-207f-494e-bbbf-4d8571ea0ff9

spec:
  ingressClassName: alb
  rules:
    - host: blackjack.spider-shlomo.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect # the name of the service
                port:
                  name: use-annotation # use the annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blackjack
                port:
                  number: 80