promtail:
  serviceAccount:
    create: true
  deployment:
    replicas: 1
  config:
    enabled: true
    logFormat: logfm
    logLevel: info
    clients:
      - url: http://10.90.100.251:3100/loki/api/v1/push # my loki server on on-premises
  sidecar:
    configReloader:
      enabled: false
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      protocol: TCP
      service:
        type: ClusterIP
        port: 1514
      