#argo-cd:
  global:
    domain: argo-cd.spider-shlomo.com

  configs:
    params:
      server.insecure: true
    cm:
      # SSO Configuration via AzureAd
      url: https://argo-cd.spider-shlomo.com
      dex.config: |
          logger:
            level: debug
            format: json
          connectors:
          - type: saml
            id: saml
            name: saml
            config:
              entityIssuer: https://argo-cd.spider-shlomo.com/api/dex/callback
              ssoURL: https://login.microsoftonline.com/a2724ae3-73eb-4b45-ba62-f432da279e2c/saml2
              caData: ${secrets.azure-sso-cert}
              redirectURI: https://argo-cd.spider-shlomo.com/api/dex/callback
              usernameAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
              emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

    # RBAC for application argo cd
    rbac:
      policy.default: role:admin
      policy.csv: |
        p, role:role:admin, *, *, *, allow
        g, "Shlomo_lab@spider-shlomo.com", role:admin
        g, "shlomobarzili@gmail.com", role:admin

  controller:
    envFrom:
      - configMapRef:
          name: Azure-AD-SSO      

  extraObjects:
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: azure-sso-cert
      namespace: argo-cd
    spec:
      refreshInterval: 1m
      secretStoreRef:
        name: aws-secret-store
        kind: ClusterSecretStore
      target:
        name: azure-sso-cert
        creationPolicy: Owner
      data:
        - secretKey: certificate
          remoteRef:
            key: Azure-AD-SSO
  

  # alb for argo cd
  server:
    ingress:
      enabled: true
      controller: aws
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/backend-protocol: HTTP
        alb.ingress.kubernetes.io/security-groups: sg-09b52735903593977
        alb.ingress.kubernetes.io/subnets: subnet-06ecc8dce3939bc67,subnet-09e3ef8e74de1afaf # Public subnetbs
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:148088962203:certificate/19d27275-0e2a-4857-95e9-79dff8e8bbd3
        alb.ingress.kubernetes.io/ssl-redirect: '443'
      aws:
        serviceType: ClusterIP # <- Used with target-type: ip
        backendProtocolVersion: GRPC

        