apiVersion: apps/v1
kind: Deployment
metadata:
  name: tigera-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: tigera-operator
  template:
    metadata:
      labels:
        name: tigera-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: tigera-operator
          image: "{{ .Values.tigeraOperator.registry }}/{{ .Values.tigeraOperator.image }}:{{ .Values.tigeraOperator.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
