tigera-operator:
  installCRDs: true
  imagePullSecrets: {}

  installation:
    enabled: true
    kubernetesProvider: "EKS"
    imagePullSecrets: []

  apiServer:
    enabled: true

  certs:
    node:
      key:
      cert:
      commonName:
    typha:
      key:
      cert:
      commonName:
      caBundle:

  resources: {}

  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

  nodeSelector:
    kubernetes.io/os: linux

  podAnnotations: {}

  podLabels: {}

  tigeraOperator:
    image: tigera/operator
    registry: quay.io
  
  calicoctl:
    image: docker.io/calico/ctl

  kubeletVolumePluginPath: None   

  kubernetesServiceEndpoint:
    host: ""
    port: "6443"