tigera-operator:
  installCRDs: true
  installation:
    enabled: true
    kubernetesProvider: EKS
  # apiServer:
  #   enabled: true
  #   namespace: default

    # calicoNetwork:
    #   # Explicitly enable VPC-CNI integration
    #   vpcCni:
    #     enabled: true
    #   # Empty ipPools to ensure Calico doesn't try to manage IP allocation
    #   ipPools: []