apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: shop-online
spec:
  serviceName: mongodb-svc  # applies only to StatefulSet
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: shlomobarzili/mongodb:latest
        args:
          - "--replSet"
          - "rs0"  # Configures Replica Set for synchronization between pods
        ports:
        - containerPort: 27017  # Default MongoDB port

        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: aws-secret  # reference from ExternalSecret
                key: MONGO_INITDB_ROOT_USERNAME
                
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aws-secret  # reference from ExternalSecret
                key: MONGO_INITDB_ROOT_PASSWORD

          - name: MONGO_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: shop-online-config  # reference from ExternalSecret
                key: MONGO_DB_HOST

        resources:
          requests:
            cpu: 100m  # Minimum CPU request
            memory: 128Mi  # Minimum memory request
          limits:
            cpu: 200m  # Maximum CPU limit
            memory: 256Mi  # Maximum memory limit

        volumeMounts:
        - name: mongo-data
          mountPath: /data/db  # Default path for MongoDB data

  volumeClaimTemplates:
  - metadata:
      name: mongo-data  # Each pod gets a uniquely named PVC (e.g., mongo-data-mongodb-0, mongo-data-mongodb-1)
    spec:
      accessModes:
        - ReadWriteOnce  # Each volume can be mounted by only one pod at a time
      storageClassName: ebs-sc  # Uses AWS EBS StorageClass
      resources:
        requests:
          storage: 33Gi  # Allocates 33Gi of storage per MongoDB pod

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: shop-online
spec:
  selector:
    app: mongodb
  clusterIP: None  # applies only to StatefulSet
  ports:
    - protocol: TCP
      port: 27017  # Default MongoDB port
      targetPort: 27017
