apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/project-blackjack.git
    path: app-of-apps/cluster-secret-store
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-secret-store
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      
    # track and sync all git changes the argo will check every 3 minutes
    automated:
      selfHeal: true # auto sync the changes to the cluster from git
      prune: true    # auto delete resources locally if thay are not in github