helmProvider:
  enabled: true # enable helm provider

keel:
  # Keel policy (all/major/minor/patch/force) - this controls the update frequency based on tag versioning
  policy: all
  trigger: poll
  pollSchedule: "@every 1m"
  images:
    - repository: shlomobarzili/blackjack # Docker Hub repository name
      tag: latest # Track the 'latest' tag, or you can use dynamic tags like commit hash

# if the repo is private you need to add the following 

# dockerRegistry:
#   enabled: true
#   name: docker.io        # Docker Hub URL
#   key: YOUR_DOCKER_HUB_USERNAME
#   secret: YOUR_DOCKER_HUB_TOKEN  # Docker Hub Access Token