apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackjack
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/project-ci-cd.git
    path: apps/blackjack
  destination:
    server: https://kubernetes.default.svc
    namespace: blackjack