apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/shlomo-b/project-ci-cd.git
    targetRevision: HEAD
    path: ./apps/
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc  # the cluster url that the argo will connect
  #  namespace: blackjack

  # to create namespace automatically | this is the blackjack namespace
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    # track and sync all git changes the argo will check every 3 minutes
    automated:
      selfHeal: true # auto sync the changes to the cluster from git
      prune: true    # auto delete resources locally if thay are not in git