apiVersion: v1
kind: Secret
metadata: 
  name: awssm-secret
  namespace: external-secrets
type: Opaque
data:
  access-key: QUtJQVNFNldLSE5TbjRVNDdQVzdH
  secret-access-key: WVUvK2VZUTl4QkdRVWdwMlg0a2lDdiszUVlvNGZSQ2pTUjZJL0pYeQ==