apiVersion: v1
kind: Secret
metadata: 
  name: awssm-secret
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  access-key: QUtJQVNFNldLSFNONFU0N1BXN0c=
  secret-access-key: WVUvK2VZUTl4QkdRVWdwMlg0a2lDdiszUVlvNGZSQ2pTUjZJL0pYeQ==