apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
# kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret # name of the secret from iam aws 
            key: access-key
            namespace: external-secrets # when serach the secret
          secretAccessKeySecretRef:
            name: awssm-secret # name of the secret from iam aws 
            key: secret-access-key
            namespace: external-secrets # when serach the secret