external-secrets:
  enabled: true
  replicaCount: 1
  installCRDs: true
  scopedRBAC: true
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      # Annotate the role from AWS
      eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/external-secrets-role
      # arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/external-secrets-role

  clusterSecretStore:
   enabled: true
   name: aws-secret-store
   namespace: external-secrets
   serviceAccount:
     name: external-secrets
     namespace: external-secrets
   provider:
     aws:
       service: SecretsManager
       region: us-east-1
       auth:
         jwt:
           serviceAccountRef:
             name: external-secrets
             namespace: external-secrets