# Adding ClusterSecretStore configuration for AWS Secrets Manager
external-secrets:
  enabled: true
  replicaCount: 1
  installCRDs: true
  scopedRBAC: true
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
      # Annotate the role from AWS
      eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/external-secrets-role
      # arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/external-secrets-role
  extraObjects:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      # kind: SecretStore
      metadata:
        name: aws-secret-store
        namespace: external-secrets
        annotations:
          argocd.argoproj.io/sync-wave: "1"
        #  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      spec:
        provider:
          aws:
            service: SecretsManager
            region: us-east-1
            auth:
              jwt:
                serviceAccountRef:
                  name: external-secrets
                  namespace: external-secrets # when serach the secrets