external-secrets:
  enabled: true
  replicaCount: 1
  installCRDs: true
  scopedRBAC: true
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
     # eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/external-secrets-role
      eks.amazonaws.com/role-arn: arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/external-secrets-role

