external-secrets: # dependencies for external-secrets
  replicaCount: 1
  provider: aws
  providerConfig:
    region: us-east-1
  scopedNamespace: blackjack
  scopedRBAC: true
  # create service account
  serviceAccount:
    create: true
    name: external-secrets