external-secrets:
  enabled: true
  replicaCount: 1
  installCRDs: true
  scopedRBAC: true
  serviceAccount:
    create: true
    name: external-secrets
    annotations:
     # role for external-secrets
      eks.amazonaws.com/role-arn: arn:aws:iam::148088962203:role/external-secrets-role