# Number of replicas for Tigera operator
replicaCount: 2

# Service account settings
serviceAccount:
  create: true
  name: tigera-operator

# Define the installation parameters and set defaults
installation:
  enabled: true
  kubernetesProvider: "aws"


apiServer:
  enabled: true

# Resource configurations
resources: {}

# NodeSelector for scheduling Tigera operator pods on Linux nodes
nodeSelector:
  kubernetes.io/os: linux

# Tolerations for allowing scheduling of Tigera operator pods
tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

# Custom pod annotations
podAnnotations: {}

# Custom pod labels
podLabels: {}

# Image configuration
tigeraOperator:
  image: tigera/operator
  registry: quay.io

# Calicoctl configuration
calicoctl:
  image: docker.io/calico/ctl
  tag: latest
