provider: aws
aws:
  zoneType: public # the zone type is public
  name: external-dns
  preferCNAME: false # the preferCNAME is false | to work with ip with a record.
policy: upsert-only  # update or create only a record without delete any record.
registry: noop       # dont needed record txt.
sources:
  - ingress          # the external-dns will look on the ingress and work with the ingress
                     # for create a record to alb.
domainFilters:
  - spider-shlomo.com # the domain in route53
logLevel: debug
txtOwnerId: ""      # its empty because we dont need record txt.
replicaCount: 2
