apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
# kind: SecretStore
metadata:
  name: aws-cluster-secret-store
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/instance: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets # when serach the secrets